### ISSUE TITLE
Is it possible to declare more than one requestHandler in solrconfig.xml?

### ISSUE THREAD

**Issue by rolfis** [IISH/oai4solr#12] opened 2016-01-11 17:03 UTC
I'm trying to create two different requestHandlers, one named "/oai-pmh/general" and one "/oai-pmh/example". I've set "oai_home" to two different subfolders in the core subfolder, and I've even tried using two different queryResponseWriters. However, the plugin seems to load the last defined oai_home static files, like Identify.xml, for both requestHandlers.

**Comment by rolfis** [comment] 2016-01-13 15:40
Just to clarify, this is my solrconfig.xml in core/scigloo where I define two requestHandlers and each of them has its own queryResponseWriter:

``` xml
<requestHandler name="/oai-pmh/general" default="false" class="org.socialhistoryservices.api.oai.OAIRequestHandler">
    <str name="wt">oai</str>
    <str name="oai_home">core/scigloo/oai/general</str>
    <str name="proxyurl">http://localhost:8080/solr/scigloo/oai-pmh/general</str>
    <str name="field_index_identifier">pubid</str>
    <str name="prefix">oai:publications.lib.chalmers.se:</str>
    <str name="field_index_set">category_set_setspec:"%s"</str>
    <str name="field_index_datestamp">modified</str>
    <str name="field_sort_datestamp">modified</str>
    <lst name="maxrecords">
        <int name="default">200</int>
        <int name="ead">1</int>
        <int name="eci">1</int>
    </lst>
    <int name="resumptionTokenExpirationInSeconds">86400</int>
    <str name="resumptionTokenSeparator">,</str>
    <str name="static_query">instanceid:1</str>
</requestHandler>

<requestHandler name="/oai-pmh/swepub" default="false" class="org.socialhistoryservices.api.oai.OAIRequestHandler">
    <str name="wt">oaiSwePub</str>
    <str name="oai_home">core/scigloo/oai/swepub</str>
    <str name="proxyurl">http://localhost:8080/solr/scigloo/oai-pmh/swepub</str>
    <str name="field_index_identifier">pubid</str>
    <str name="prefix">oai:services.scigloo.org:</str>
    <str name="field_index_set">category_set_setspec:"%s"</str>
    <str name="field_index_datestamp">modified</str>
    <str name="field_sort_datestamp">modified</str>
    <lst name="maxrecords">
        <int name="default">200</int>
        <int name="ead">1</int>
        <int name="eci">1</int>
    </lst>
    <int name="resumptionTokenExpirationInSeconds">86400</int>
    <str name="resumptionTokenSeparator">,</str>
    <str name="static_query">instanceid:*</str>
</requestHandler>

<queryResponseWriter name="oai" class="org.socialhistoryservices.api.oai.OAIQueryResponseWriter" />
<queryResponseWriter name="oaiSwePub" class="org.socialhistoryservices.api.oai.OAIQueryResponseWriter" />
```

After I added some INFO logging to the Java code I can see that the static files gets loaded for each WT:

INFO  org.socialhistoryservices.api.oai.OAIRequestHandler  oai_home=/usr/local/solr/core/scigloo/oai/general
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/general/Identify.xml for wt:oai
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/general/ListMetadataFormats.xml for wt:oai
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/general/ListSets.xml for wt:oai

INFO  org.socialhistoryservices.api.oai.OAIRequestHandler oai_home=/usr/local/solr/core/scigloo/oai/swepub
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/swepub/Identify.xml for wt:oaiSwePub
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/swepub/ListMetadataFormats.xml for wt:oaiSwePub
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler Loaded /usr/local/solr/core/scigloo/oai/swepub/ListSets.xml for wt:oaiSwePub

But when I hit the first defined requestHandler:
GET /solr/scigloo/oai-pmh/general?verb=Identify

The logging I've added says it's working against the second defined WT: 
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler WT: oaiSwePub

And I get the (wrong) Identify.xml that is located in oai/swepub/Identify.xml.

And the second:
GET /solr/scigloo/oai-pmh/swepub?verb=Identify

Works against the second:
INFO  org.socialhistoryservices.api.oai.OAIRequestHandler WT: oaiSwePub

Simply asking, is this supposed to work? 
What could be wrong?

**Comment by lwo** [comment] 2016-01-13 16:47
The configuration in itself is good, but I never expected a multi request handler usage hence you encounter the problem. The problem is the static:
https://github.com/IISH/oai4solr/blob/4.x-1.0/oai2-plugin/src/main/java/org/socialhistoryservices/api/oai/Parameters.java#L16

So in its current form, the plugin only allows one request handler.

Should I change this issue status to a feature request for multiple handlers ?

**Comment by rolfis** [comment] 2016-01-13 22:24
Yes, please. I think it would make a wonderful and useful feature. Do you think it would need a lot of rewriting the static store?

**Comment by lwo** [comment] 2016-01-14 10:06
If we can use the handler name value as a prefix for each key, then not much. Or otherwise some refactoring. It needs extra unit testing... and some time to plan it in after hours.

**Comment by moostra** [comment] 2017-10-26 14:00
Hi, First of all: nice project! We tried to implement it on a multi-core Solr environment and ran into the same sort of problems as @rolfis. I suppose this is due to the same problem?

**Comment by lwo** [comment] 2017-10-30 19:19
Fixed by:
https://github.com/IISH/oai4solr/commit/541f4399050147d131ee2fa01bfd734bc5813560
https://github.com/IISH/oai4solr/commit/5b023502081cc61004bc8b466c16d50bdc762fce
https://github.com/IISH/oai4solr/commit/ac1bdf79728017297f34cd384cf2e93679640a77

**Closed as completed by lwo** 2017-10-30 19:19 UTC
Labels: enhancement
